### PR TITLE
improvement/typescript

### PR DESCRIPTION
**Pull request by Ty3uK**
- Switched from outdated typescript-compiler to native tsc. After this we have support of module resolutions and all new things of TypeScript
- Added ability to pass options to tsc through 'tsc' section of pingy.json. Example file:
```
{
    "name": "pingy",
    "exportDir": "dist",
    "minify": true,
    "compile": true,
    "exclusions": [
        {
            "path": "node_modules",
            "action": "exclude",
            "type": "dir"
        }
    ],
    "tsc": {
        "module": "System",
        "target": "es5",
        "lib": ["dom", "es2015"]
    }
}
```

### CODE REVIEW

**Comment by Ty3uK** [comment]
What's wrong with AppVeyor? Tests on unix passed successfully, but on Windows they crashes on @pingy/scaffold tests

**Comment by davej** [comment]
Thanks!

> What's wrong with AppVeyor? Tests on unix passed successfully, but on Windows they crashes on tests

Yeah, the appveyor test have been failing for a while (#75) although they pass when I run them on my Windows 7 VM, I haven't got around to figuring out why yet.

How does this work with `pingy dev`? Should `pingy dev` also read `options.tsc`?

**Comment by davej** [comment]
Could you also add docs here please: https://github.com/pingyhq/pingy-cli/blob/master/packages/accord/docs/typescript.md

**Comment by Ty3uK** [comment]
Ok, i’ll check it tomorrow 😤

**Comment by Ty3uK** [comment]
Done!

**Comment by davej** [comment]
Awesome! If `tsc` isn't specified then are the defaults reasonable? Should `pingy init` populate the `tsc` property with some defaults when typescript is chosen? What are your thoughts?

**Comment by Ty3uK** [comment]
Out of the box typescript have full support transpile to ES5, CommonJS modules, so basic `tsc` section isn’t needed

**Comment by Ty3uK** [comment]
When i say “typescript” i means tsc, typescript compiler 🙂

**Comment by davej** [comment]
👍. I'll merge and release later this week. Thanks for the PR.

**Comment by Ty3uK** [comment]
No problems, buddy. Thank you too! 🤝

**Comment by davej** [comment]
Published in `0.12`

**Comment by davej** [comment]
Pushed a fix for #84 and [this](https://twitter.com/pambuk/status/941364487428431872) in afabc357b4c92547d5eb97713dd3fda8884eec39.

**Pull request merged**
